title:              "Code & Beyond"
email:              cheese.choi@gmail.com
description:        Code, systems, and beyond
author:             Jongmyeong
baseurl:            ""
url:                "https://cheesechoi.github.io"

# Social Profiles
twitter_username:   cheese_choi
github_username:    cheesechoi
facebook_username:
instagram_username:  
linkedin_username: cheese-choi

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # Replace with your actual Google Analytics ID
# For Google Analytics 4, use format: G-XXXXXXXXXX
google_analytics:   G-9HS0BJRSCT # Enter your Google Analytics 4 ID (G-XXXXXXXXXX) or Universal Analytics ID (UA-XXXXXXXXX-X)

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/tech/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
